/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mainPackage.Pannels.Factory;

import com.mainPackage.MainProgram;
import dao.CashLedgerDao;
import java.math.BigDecimal;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import model.CashLedgerModel;
import java.util.List;
import javax.swing.SwingUtilities;
/**
 *
 * @author Bladestorm
 */
public class CashDetailse extends javax.swing.JPanel {

    /**
     * Creates new form CashDetailse
     */
    
    CashLedgerDao cashledgerdao = new CashLedgerDao();
    public CashDetailse() {
        initComponents();
        
        DefaultTableModel model = (DefaultTableModel) tblcashledger.getModel();
        
        List<CashLedgerModel> cashledger = cashledgerdao.getCashDetails();
        BigDecimal balance = new BigDecimal(0);
       BigDecimal damount = new BigDecimal(0);
       BigDecimal camount = new BigDecimal(0);
       BigDecimal zero = new BigDecimal(0);
       String sbalance = null;
       Iterator<CashLedgerModel> iter = cashledger.iterator();
        
        
        while (iter.hasNext()) { 
            CashLedgerModel lsmodel = iter.next();
            
             damount = damount.add(lsmodel.getDebit());
            camount = camount.add(lsmodel.getCredit());
            balance = damount.subtract(camount);
            int result = balance.compareTo(zero);
             if (result == 1) {
                sbalance = balance.toString() + "  DR";
            } else {
                sbalance = balance.abs().toString() + "  CR";

            }
//            if(lsmodel.getParticular().equalsIgnoreCase("Cash Deposit") || lsmodel.getParticular().equalsIgnoreCase("Product Payment")){
//                model.addRow(new Object[]{lsmodel.getDate(),lsmodel.getParticular(),"",lsmodel.getCredit(),sbalance});
//            }else{
//                model.addRow(new Object[]{lsmodel.getDate(),lsmodel.getParticular(),lsmodel.getDebit(),"",sbalance});
//            }

            model.addRow(new Object[]{lsmodel.getDate(),lsmodel.getParticular(),lsmodel.getDebit(),lsmodel.getCredit(),sbalance});
        }
        model.addRow(new Object[]{"","","","",""});
        model.addRow(new Object[]{"","Total",damount,camount,sbalance});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcashledger = new javax.swing.JTable();
        btnBack = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Cash Ledger Details");

        tblcashledger.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblcashledger.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Particular", "Debit", "Credit", "Balance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblcashledger.setRowHeight(25);
        tblcashledger.setRowMargin(2);
        jScrollPane1.setViewportView(tblcashledger);
        if (tblcashledger.getColumnModel().getColumnCount() > 0) {
            tblcashledger.getColumnModel().getColumn(0).setResizable(false);
            tblcashledger.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblcashledger.getColumnModel().getColumn(1).setResizable(false);
            tblcashledger.getColumnModel().getColumn(1).setPreferredWidth(200);
            tblcashledger.getColumnModel().getColumn(2).setResizable(false);
            tblcashledger.getColumnModel().getColumn(2).setPreferredWidth(80);
            tblcashledger.getColumnModel().getColumn(3).setResizable(false);
            tblcashledger.getColumnModel().getColumn(3).setPreferredWidth(80);
            tblcashledger.getColumnModel().getColumn(4).setPreferredWidth(80);
        }

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/goback.png"))); // NOI18N
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(291, 291, 291)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 979, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(286, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
        MainProgram.mainframe.mainPane.remove(this);
        MainProgram.mainframe.mainPane.add(new Balance());
        SwingUtilities.updateComponentTreeUI(MainProgram.mainframe.mainPane);
    }//GEN-LAST:event_btnBackMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblcashledger;
    // End of variables declaration//GEN-END:variables
}
