/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mainPackage.Pannels.Entry;

import com.mainPackage.MainProgram;
import com.mainPackage.Pannels.Dashboard;
import dao.BankDepositDao;
import dao.BankLedgerDao;
import dao.CashDepositDao;
import dao.CashLedgerDao;
import dao.ExpensesDao;
import dao.IncomeDao;
import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import model.BankDepositMode;
import model.BankLedgerModel;
import java.util.List;
import model.CashDepositModel;
import model.CashLedgerModel;
import model.DailyBookModel;

/**
 *
 * @author Bladestorm
 */
public class BalanceEntry extends javax.swing.JPanel {
    Date date = new Date();
    DateFormat dateformat = new SimpleDateFormat("yyyy/MM/dd");

    /**
     * Creates new form BalanceEntry
     */
    
    String sdate;
    Date nDate;
    BankDepositDao bankdepositdao = new BankDepositDao();
    BankDepositMode bankdepmodel = new BankDepositMode();
    
    CashDepositDao cashdepositdao = new CashDepositDao();
    CashDepositModel cashdepmodel = new CashDepositModel();
    
    BankLedgerDao bankledgerdao = new BankLedgerDao();
    BankLedgerModel bankledgermodel = new BankLedgerModel();
    
    //CashLedger
    CashLedgerDao cashledgerdao = new CashLedgerDao();
    CashLedgerModel cashledgermodel = new CashLedgerModel();
    
    //Daily Book
    IncomeDao indao = new IncomeDao();
    ExpensesDao exdao = new ExpensesDao();
    DailyBookModel dailybookmodel = new DailyBookModel();
    
    public BalanceEntry() {
        initComponents();
        bankdepositdao.createTable();
        bankledgerdao.createTable();
        
        //Cash deposit
        cashdepositdao.createTable();
        //Cash ledger
        cashledgerdao.createTable();
        indao.createTable();
        exdao.createTable();
        
        txtDate.setText(dateformat.format(date));
        txtCashDate.setText(dateformat.format(date));
        
        //Bank name list
        List<String> blst = bankdepositdao.getBankname();
        Iterator<String> ls = blst.iterator();
        while(ls.hasNext()){
            txtBankName.addItem(ls.next());
        }
    }

     public Date getnDate() {
        sdate = txtDate.getText();
        try {
            /*final*/ nDate = dateformat.parse(sdate);
        } catch (ParseException dateexception) {
            JOptionPane.showMessageDialog(null, "Please enter Date in the Format YYYY/MM/DD");
        }
        return nDate;
    }
     
      public Date getnCashDate() {
        sdate = txtCashDate.getText();
        try {
            /*final*/ nDate = dateformat.parse(sdate);
        } catch (ParseException dateexception) {
            JOptionPane.showMessageDialog(null, "Please enter Date in the Format YYYY/MM/DD");
        }
        return nDate;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnBack = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtBankAmount = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        txtDeposit = new javax.swing.JButton();
        txtBankName = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtCashDate = new javax.swing.JTextField();
        btnCashDeposit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtCashAmount = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/goback.png"))); // NOI18N
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel8.setText("Date");

        jLabel9.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel9.setText("Amount");

        jLabel10.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel10.setText("Bank Name");

        txtDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDateFocusLost(evt);
            }
        });

        txtDeposit.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        txtDeposit.setText("Deposit");
        txtDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDepositActionPerformed(evt);
            }
        });

        txtBankName.setEditable(true);
        txtBankName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(txtBankAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtBankName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(13, 13, 13)
                                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(txtDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(557, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBankName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBankAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(txtDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Bank Deposit", jPanel1);

        jLabel3.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel3.setText("Date");

        txtCashDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCashDateFocusLost(evt);
            }
        });

        btnCashDeposit.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        btnCashDeposit.setText("Submit");
        btnCashDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashDepositActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel5.setText("Amount");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(txtCashAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(txtCashDate, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(btnCashDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(557, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCashDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCashAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnCashDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cash at hand", jPanel2);

        jLabel2.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jLabel2.setText("Deposit");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1047, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
        MainProgram.mainframe.mainPane.remove(this);
        MainProgram.mainframe.mainPane.add(new Dashboard());
        SwingUtilities.updateComponentTreeUI(MainProgram.mainframe.mainPane);
    }//GEN-LAST:event_btnBackMouseClicked

    private void txtDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepositActionPerformed
        // TODO add your handling code here:
        String sDate = txtDate.getText();
        Object oBankName = txtBankName.getSelectedItem();
        String sBankName = oBankName.toString();
        String sAmount = txtBankAmount.getText();
        
        if(sDate.isEmpty()){
            JOptionPane.showMessageDialog(null, "Date is empty !!");
        }else if(!sDate.matches("[0-9/_]+")){
            JOptionPane.showMessageDialog(null, "Date not valid !!");
        } else if(!sDate.matches("\\d{4}/\\d{1,2}/\\d{1,2}")){
            JOptionPane.showMessageDialog(null, "Date not valid date should be YYYY/MM/DD");
        }
        else if(sBankName.isEmpty()){
            JOptionPane.showMessageDialog(null, "Bank name is empty !!");
        }
        else if(sAmount.isEmpty()){
            JOptionPane.showMessageDialog(null, "Amount is empty !!");
        }else if(!sAmount.matches("[0-9_]+")){
            JOptionPane.showMessageDialog(null, "Amount not valid !!");
        }
        else{
         if(JOptionPane.showConfirmDialog(null, "Are you Sure want to Deposit"  +"\n Date :- " +sDate + "\n Bank Name  " + sBankName + "\n Amount  " +sAmount,"Deposit", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
             
        
        //Bank Ledger
        bankledgermodel.setDate(getnDate());
        bankledgermodel.setBankname(sBankName);
        bankledgermodel.setParticular("Deposit");
        bankledgermodel.setDebit(new BigDecimal(0));
        bankledgermodel.setCredit(new BigDecimal(sAmount));
        bankledgerdao.insert(bankledgermodel);
        
          //BankBalance
        bankdepmodel.setBankname(sBankName);
        bankdepmodel.setAmount(new BigDecimal(sAmount));
        bankdepositdao.bInsert(bankdepmodel);
        //Daily Book cheque
        dailybookmodel.setDate(getnDate());
        dailybookmodel.setParticular("Cheque deposit " + sBankName);
        dailybookmodel.setAmount(new BigDecimal(sAmount));
        indao.insertIncom(dailybookmodel);
       JOptionPane.showMessageDialog(null, "Amount Deposit Success"); 
       
         }else{
             JOptionPane.showMessageDialog(null, "Deposit Cancelled"); 
         }
         txtBankAmount.setText("");
         
        }
    }//GEN-LAST:event_txtDepositActionPerformed

    private void txtBankNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankNameActionPerformed

    private void btnCashDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashDepositActionPerformed
        // TODO add your handling code here:
        sdate = txtCashDate.getText();
        String samount = txtCashAmount.getText();
        if(sdate.isEmpty()){
            JOptionPane.showMessageDialog(null, "Date is Empty !!");
        }else if(!sdate.matches("\\d{4}/\\d{1,2}/\\d{1,2}")){
            JOptionPane.showMessageDialog(null, "Date not valid date should be YYYY/MM/DD");
        }
        else if(!sdate.matches("[0-9/_]+")){
            JOptionPane.showMessageDialog(null, "Date not valid !!");
        }else  if(samount.isEmpty()){
            JOptionPane.showMessageDialog(null, "Amount is Empty !!");
        }else if(!samount.matches("[0-9_]+")){
            JOptionPane.showMessageDialog(null, "Enter digits in amount !!");
        }else{
            if(JOptionPane.showConfirmDialog(null, "Are you sure want to deposit ?" +"\n Date :-" + sdate + "\n Amount  RS :- " + samount,"Cash Deposit",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
              
               
               //cash deposit ledger
               cashledgermodel.setDate(getnCashDate());
               cashledgermodel.setParticular("Cash Deposit");
               cashledgermodel.setDebit(new BigDecimal(0));
               cashledgermodel.setCredit(new BigDecimal(samount));
                cashledgerdao.insert(cashledgermodel);
                
                //cash deposit
                 cashdepmodel.setParticular("Cash Deposit");
               cashdepmodel.setCash(new BigDecimal(samount));
               cashdepositdao.insert(cashdepmodel);
               
               //Daily book
               dailybookmodel.setDate(getnCashDate());
               dailybookmodel.setParticular("Cash Deposit");
               dailybookmodel.setAmount(new BigDecimal(samount));
               indao.insertIncom(dailybookmodel);
                JOptionPane.showMessageDialog(null, "success");
            }else{
                JOptionPane.showMessageDialog(null, "Balance not entry !!");
            }
            txtCashAmount.setText("");
        } 
    }//GEN-LAST:event_btnCashDepositActionPerformed

    private void txtDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDateFocusLost
        // TODO add your handling code here:
           sdate = txtDate.getText();
        try {
            /*final*/ nDate = dateformat.parse(sdate);
        } catch (ParseException dateexception) {
            JOptionPane.showMessageDialog(null, "Please enter Date in the Format YYYY/MM/DD");
        }
    }//GEN-LAST:event_txtDateFocusLost

    private void txtCashDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCashDateFocusLost
        // TODO add your handling code here:
            sdate = txtCashDate.getText();
        try {
            /*final*/ nDate = dateformat.parse(sdate);
        } catch (ParseException dateexception) {
            JOptionPane.showMessageDialog(null, "Please enter Date in the Format YYYY/MM/DD");
        }
    }//GEN-LAST:event_txtCashDateFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack;
    private javax.swing.JButton btnCashDeposit;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtBankAmount;
    private javax.swing.JComboBox<String> txtBankName;
    private javax.swing.JTextField txtCashAmount;
    private javax.swing.JTextField txtCashDate;
    private javax.swing.JTextField txtDate;
    private javax.swing.JButton txtDeposit;
    // End of variables declaration//GEN-END:variables
}
