/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mainPackage.Pannels.Entry;

import com.mainPackage.MainProgram;
import com.mainPackage.Pannels.Dashboard;
import dao.ItemSalesDao;
import dao.ItemStockDao;
import dao.ItemStockDetailsDao;
import dao.SaleReceiptDao;
import dao.SalesDao;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import model.ItemSaleModel;
import model.ItemStockDetailsModel;
import model.ItemStockModel;
import model.SaleEntryModel;
import model.SaleReceiptModel;

/**
 *
 * @author Bladestorm
 */
public class SalesEntry extends javax.swing.JPanel {

    //Data Types
    String sDate, sBillno, sClientName, sAddress, sPhone, sTotal, sVat, sNetAmount, sItem, sQty, sFactoryPrice, sSellingPrice, sAmount, sProfit, sTTotal;
    int nQty, nSellingPrice, nFactoryPrice, nbillno;
    Date nDate;
    BigDecimal bg_sellingPrice, bg_profit, bg_total;

    /**
     * Creates new form SalesEntry
     */
    Date date = new Date();
    DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");

    //Item sales Dao
    ItemSalesDao itSaleDao = new ItemSalesDao();
    ItemSaleModel itSalemodel = new ItemSaleModel();

    //Sales Entry Dao
    SalesDao saledao = new SalesDao();
    SaleEntryModel salemodel = new SaleEntryModel();

    //Sales Receipt model
    SaleReceiptModel receiptmodel = new SaleReceiptModel();
    SaleReceiptDao receiptdao = new SaleReceiptDao();

    //ItemStock to decrease
    ItemStockModel itemstockmodel = new ItemStockModel();
    ItemStockDao itemstock = new ItemStockDao();

    //ItemStock Details
    ItemStockDetailsModel itemdetailmodel = new ItemStockDetailsModel();
    ItemStockDetailsDao itemdetaildao = new ItemStockDetailsDao();

    public SalesEntry() {
        itSaleDao.createTable();
        saledao.createTable();
        receiptdao.createTable();

        initComponents();
        //Item JComb Box
        txtItem.setSelectedIndex(-1);
        txtDate.setText(dateFormat.format(date));
        List<String> allItem = itemstock.getAlItems();
        Iterator<String> itemIterator = allItem.iterator();
        while (itemIterator.hasNext()) {
            txtItem.addItem(itemIterator.next());
        }

        //Clint name JCombo Box
        List<String> clients = saledao.getClientName();
        Iterator<String> ab = clients.iterator();
        while (ab.hasNext()) {
            txtCompanyName.addItem(ab.next());
        }

    }

    public int getSum() {
        int sum = 0;
        int rowsCount = tblProduct.getRowCount();
        for (int i = 0; i < rowsCount; i++) {
            sum = sum + Integer.parseInt(tblProduct.getValueAt(i, 4).toString());
        }
        return sum;
    }

    public BigDecimal getNetAmount() {

        String sTotal = txtTotal.getText();
        String sDiscount = txtDiscount.getText();
        String sVat = txtVat.getText();
        BigDecimal bgDiscount = new BigDecimal(sDiscount);

        BigDecimal y;
        BigDecimal bgFTotal = new BigDecimal(sTotal);
        BigDecimal bgTotal = bgFTotal.subtract(bgDiscount);
        BigDecimal hundred = new BigDecimal(100);
        BigDecimal bgNetAmount;
        BigDecimal bgVat;
        BigDecimal bgFixVat;
        if (sVat.isEmpty()) {
            y = new BigDecimal(0);
            bgFixVat = y.divide(hundred);
            bgNetAmount = bgFixVat.multiply(bgTotal).add(bgTotal);
            return bgNetAmount;

        } else {
            bgVat = new BigDecimal(sVat);
            bgFixVat = bgVat.divide(hundred);
            bgNetAmount = bgFixVat.multiply(bgTotal).add(bgTotal);
            return bgNetAmount;
        }

    }

    public Date getnDate() {
        sDate = txtDate.getText();
        try {
            /*final*/ nDate = dateFormat.parse(sDate);
        } catch (ParseException dateexception) {
            JOptionPane.showMessageDialog(null, "Please enter Date in the Format YYYY/MM/DD");
        }
        return nDate;
    }

    public int getnBill() {
        sBillno = txtBillno.getText();
        nbillno = Integer.parseInt(sBillno);
        return nbillno;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtBillno = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCompanyName = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtVat = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtNetAmount = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtItem = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFactoryPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSellingPrice = new javax.swing.JTextField();
        txtAmount = new javax.swing.JTextField();
        btnAddItem = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnTotal = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        btnCalNetAmt = new javax.swing.JButton();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/goback.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel2.setText("Date");

        txtDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDateFocusLost(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel10.setText("Bill no");

        jLabel11.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel11.setText("Client Name ");

        txtCompanyName.setEditable(true);
        txtCompanyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompanyNameActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel12.setText("Address");

        jLabel13.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel13.setText("Phone no");

        jLabel14.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel14.setText("Total Amount");

        txtTotal.setEditable(false);

        jLabel15.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel15.setText("VAT  %");

        jLabel16.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel16.setText("Net Amount");

        txtNetAmount.setEditable(false);
        txtNetAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNetAmountActionPerformed(evt);
            }
        });

        btnSubmit.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel17.setText("Discount");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(13, 13, 13)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(txtBillno, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(txtVat, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNetAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(124, 124, 124)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(13, 13, 13)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(13, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBillno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNetAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(617, Short.MAX_VALUE)))
        );

        jLabel3.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel3.setText("Item");

        jLabel4.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel4.setText("QTY (Dorzon)");

        txtQuantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQuantityFocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel5.setText("Factory Price");

        jLabel6.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel6.setText("Sell Price");

        txtAmount.setEditable(false);

        btnAddItem.setText("Add Items");
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel8.setText("Product Details");

        btnTotal.setText("Total");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAddItem)
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTotal)
                        .addGap(88, 88, 88))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(146, 146, 146)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(100, 100, 100)
                            .addComponent(txtItem, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtFactoryPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtSellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(160, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnTotal)))
                .addGap(47, 47, 47)
                .addComponent(btnAddItem)
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtFactoryPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtSellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(73, Short.MAX_VALUE)))
        );

        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tblProduct.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.n", "Product", "QTY", "Price", "Total Price", "Profit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProduct.setRowHeight(25);
        tblProduct.setSelectionBackground(new java.awt.Color(153, 255, 153));
        tblProduct.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblProduct);
        if (tblProduct.getColumnModel().getColumnCount() > 0) {
            tblProduct.getColumnModel().getColumn(0).setResizable(false);
            tblProduct.getColumnModel().getColumn(1).setResizable(false);
            tblProduct.getColumnModel().getColumn(2).setResizable(false);
            tblProduct.getColumnModel().getColumn(3).setResizable(false);
            tblProduct.getColumnModel().getColumn(4).setResizable(false);
            tblProduct.getColumnModel().getColumn(5).setResizable(false);
        }

        btnCalNetAmt.setBackground(new java.awt.Color(102, 102, 255));
        btnCalNetAmt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCalNetAmt.setForeground(new java.awt.Color(51, 51, 255));
        btnCalNetAmt.setText("Calculate Net Amount");
        btnCalNetAmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalNetAmtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(238, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCalNetAmt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(btnCalNetAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        MainProgram.mainframe.mainPane.remove(this);
        MainProgram.mainframe.mainPane.add(new Dashboard());
        SwingUtilities.updateComponentTreeUI(MainProgram.mainframe.mainPane);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void txtCompanyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompanyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompanyNameActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:

        try {
            txtNetAmount.setText(getNetAmount().setScale(2, RoundingMode.DOWN).toString());
        } catch (NumberFormatException e) {
//            JOptionPane.showMessageDialog(null, "Enter vat");
        }

        sDate = txtDate.getText();
        sBillno = txtBillno.getText();
        Object Oclintname = txtCompanyName.getSelectedItem();
        sClientName = Oclintname.toString();
        sPhone = txtPhone.getText();
        sAddress = txtAddress.getText();
        sTotal = txtTotal.getText();
        sVat = txtVat.getText();
        sNetAmount = txtNetAmount.getText();
        sQty = txtQuantity.getText();

        if (sDate.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Date is Empty !!");
        } else if (!sDate.matches("[0-9/_]+")) {
            JOptionPane.showMessageDialog(null, "Date Invalid !!");
        } else if (!sDate.matches("\\d{4}/\\d{1,2}/\\d{1,2}")) {
            JOptionPane.showMessageDialog(null, "Date not valid date should be YYYY/MM/DD");
        } else if (sBillno.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Bill no is Empty !!");
        } else if (!sBillno.matches("[0-9_]+")) {
            JOptionPane.showMessageDialog(null, "Bill no Invalid !! Enter Digits");
        } else if (sClientName.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Clint Name is Empty !!");
        } else if (sAddress.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Address is Empty !!");
        } else if (sPhone.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Phone no. is Empty !!");
        } else if (!sPhone.matches("[0-9_]+")) {
            JOptionPane.showMessageDialog(null, "Phone no not valid !!");
        } else if (sTotal.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Amount is empty, First entry Item details !!");
        } else if (sVat.isEmpty()) {
            JOptionPane.showMessageDialog(null, "VAT is empty !!");
        } else if (!sVat.matches("[0-9._]+")) {
            JOptionPane.showMessageDialog(null, "VAT Not Valid !!");
        } else if (sNetAmount.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Net Amount is empty, Click Calculate Net Amount buttom !!");
        } else {
            if (JOptionPane.showConfirmDialog(null, "   Sales Details   " + "\n Date :- " + sDate + "\n Bill no :- " + sBillno + "\n Client Name :- " + sClientName + "\n Address :- " + sAddress + "\n Total Amount :- " + sTotal + "\n VAT (%)  " + sVat + "\n Net Amount :- " + sNetAmount, "Title", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

                int rows = tblProduct.getRowCount();

                for (int row = 0; row < rows; row++) {
                    sItem = (String) tblProduct.getValueAt(row, 1);
                    sQty = (String) tblProduct.getValueAt(row, 2);
                    int nQty1 = Integer.parseInt(sQty);
                    sSellingPrice = (String) tblProduct.getValueAt(row, 3);
                    bg_sellingPrice = new BigDecimal(sSellingPrice);
                    sTTotal = (String) tblProduct.getValueAt(row, 4);
                    bg_total = new BigDecimal(sTTotal);
                    sProfit = (String) tblProduct.getValueAt(row, 5);
                    bg_profit = new BigDecimal(sProfit);

                    //Sales Item Details
                    itSalemodel.setDate(getnDate());
                    itSalemodel.setBillno(getnBill());
                    itSalemodel.setClientname(sClientName);
                    itSalemodel.setItem(sItem);
                    itSalemodel.setItemprice(bg_sellingPrice);
                    itSalemodel.setQuantity(nQty1);
                    itSalemodel.setTotalprice(bg_total);
                    itSalemodel.setProfit(bg_profit);
                    itSaleDao.insert(itSalemodel);

                    //to Decrease copy stock
                    itemstockmodel.setItemname(sItem);
                    itemstockmodel.setQuantity(new BigDecimal(sQty));
                    itemstock.itemDecrease(itemstockmodel);
                    
                    //insert item details
              itemdetailmodel.setDate(getnDate());
              itemdetailmodel.setItemname(sItem);
              itemdetailmodel.setIncrement(new BigDecimal(0));
              itemdetailmodel.setDecrement(new BigDecimal(sQty));
              itemdetaildao.insert(itemdetailmodel);

                }
                salemodel.setDate(getnDate());
                salemodel.setBillno(getnBill());
                salemodel.setClientname(sClientName);
                salemodel.setAddress(sAddress);
                salemodel.setPhone(sPhone);
                salemodel.setTotalamt(new BigDecimal(sTotal));
                salemodel.setVat(new BigDecimal(sVat));
                salemodel.setNetamt(new BigDecimal(sNetAmount));
                saledao.insert(salemodel);

                //Sales Receipt for ledger
                receiptmodel.setDate(getnDate());
                receiptmodel.setClientname(sClientName);
                receiptmodel.setParticular("Sales Account");
                receiptmodel.setVchtype("Bill No");
                receiptmodel.setVchno(getnBill());
                receiptmodel.setDebit(new BigDecimal(sNetAmount));
                receiptmodel.setCredit(new BigDecimal("0"));
                receiptdao.insert(receiptmodel);

                MainProgram.mainframe.mainPane.remove(this);
                MainProgram.mainframe.mainPane.add(new SalesEntry());
                SwingUtilities.updateComponentTreeUI(MainProgram.mainframe);

                JOptionPane.showMessageDialog(null, "Record Insert");
            } else {
                JOptionPane.showMessageDialog(null, "Record not saved !!!");
            }

        }


    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDateFocusLost
        // TODO add your handling code here:
        sDate = txtDate.getText();
        try {
            nDate = dateFormat.parse(sDate);
        } catch (ParseException dateexception) {
            JOptionPane.showMessageDialog(null, "Please enter Date in the Format YYYY/MM/DD");
        }
    }//GEN-LAST:event_txtDateFocusLost

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        // TODO add your handling code here:
        Object OItem = txtItem.getSelectedItem();
        sItem = OItem.toString();
        sQty = txtQuantity.getText();
        sSellingPrice = txtSellingPrice.getText();
        sFactoryPrice = txtFactoryPrice.getText();
        sAmount = txtAmount.getText();

        if (sItem.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Select Items");
        } else if (sQty.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Quantity is Empty !!");
        } else if (!sQty.matches("[0-9_]+")) {
            JOptionPane.showMessageDialog(null, "Quantity not valid !! Enter digits");
        } else if (!itemstock.ItemStockCheck(sItem, new BigDecimal(sQty))) {
            JOptionPane.showMessageDialog(null, "Quantity is Greater then Stock");
        } else if (sFactoryPrice.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Factory Price is Empty !!");
        } else if (!sFactoryPrice.matches("[0-9_]+")) {
            JOptionPane.showMessageDialog(null, "Factory Price not valid !! Enter digits");
        } else if (sSellingPrice.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selling Price is Empty !!");
        } else if (!sSellingPrice.matches("[0-9_]+")) {
            JOptionPane.showMessageDialog(null, "Selling Price not valid !! Enter digits");
        } else if (sAmount.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Click Total button Amount is Empty !!");
        } else if (!sAmount.matches("[0-9_]+")) {
            JOptionPane.showMessageDialog(null, "Amount Price not valid !! Enter digits");
        } else {
            //Integer
            nQty = Integer.parseInt(sQty);
            BigDecimal bg_qty = new BigDecimal(nQty);
            nSellingPrice = Integer.parseInt(sSellingPrice);
            BigDecimal bg_sp = new BigDecimal(nSellingPrice);

            nFactoryPrice = Integer.parseInt(sFactoryPrice);
//            int c = nQty * nSellingPrice;
            BigDecimal c = bg_qty.multiply(bg_sp);
            String fc = c.toString();

            int profit = nSellingPrice - nFactoryPrice;
            int fprofit = profit * nQty;
            BigDecimal bgfprofit = new BigDecimal(fprofit);
            String sbfprofit = bgfprofit.toString();

            DefaultTableModel model = (DefaultTableModel) tblProduct.getModel();
            Object[] add = new Object[6];
            int i = 1;
            add[0] = 1 + tblProduct.getRowCount();
            add[1] = sItem;
            add[2] = sQty;
            add[3] = sSellingPrice;
            add[4] = fc;
            add[5] = sbfprofit;
            model.addRow(add);

            txtTotal.setText(Integer.toString(getSum()));
            txtAmount.setText("");
        }


    }//GEN-LAST:event_btnAddItemActionPerformed

    private void txtQuantityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQuantityFocusLost
        // TODO add your handling code here:
        Object oItem = txtItem.getSelectedItem();
        sItem = oItem.toString();
        sQty = txtQuantity.getText();
        BigDecimal bg_qty = new BigDecimal(sQty);
        if (itemstock.ItemStockCheck(sItem, bg_qty)) {

        } else {
            JOptionPane.showMessageDialog(null, "We dont have enought stock !!");
        }
    }//GEN-LAST:event_txtQuantityFocusLost

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        // TODO add your handling code here:
        Object oItem = txtItem.getSelectedItem();
        sItem = oItem.toString();
        sQty = txtQuantity.getText();
        sSellingPrice = txtSellingPrice.getText();
        //Integer
        nQty = Integer.parseInt(sQty);
        nSellingPrice = Integer.parseInt(sSellingPrice);

        BigDecimal bg_Qty = new BigDecimal(nQty);
        BigDecimal bg_sp = new BigDecimal(nSellingPrice);

        txtAmount.setText(bg_Qty.multiply(bg_sp).toString());

        //To check Item 
        int rows = tblProduct.getRowCount();
        for (int row = 0; row < rows; row++) {
            String srimsize = (String) tblProduct.getValueAt(row, 1);

            if (sItem.equals(srimsize)) {
                JOptionPane.showMessageDialog(null, "Item already added");
                txtAmount.setText("");
            } else {

            }
        }


    }//GEN-LAST:event_btnTotalActionPerformed

    private void btnCalNetAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalNetAmtActionPerformed
        // TODO add your handling code here:
        try {
            txtNetAmount.setText(getNetAmount().setScale(2, RoundingMode.DOWN).toString());
        } catch (NumberFormatException e) {
//            JOptionPane.showMessageDialog(null, "Enter vat");
        }
    }//GEN-LAST:event_btnCalNetAmtActionPerformed

    private void txtNetAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNetAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNetAmountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnCalNetAmt;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProduct;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtBillno;
    private javax.swing.JComboBox<String> txtCompanyName;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtFactoryPrice;
    private javax.swing.JComboBox<String> txtItem;
    private javax.swing.JTextField txtNetAmount;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSellingPrice;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtVat;
    // End of variables declaration//GEN-END:variables
}
