/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mainPackage.Pannels.Administrator;

import com.mainPackage.MainProgram;
import com.mainPackage.Pannels.Administrator.admindash;
import dao.AdminDao;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import utills.DbConnection;

/**
 *
 * @author Bladestorm
 */
public class LoginDetails extends javax.swing.JPanel {

    DbConnection db = new DbConnection();
    AdminDao adminDao = new AdminDao();

    /**
     * Creates new form LoginDetails
     */
    public LoginDetails() {
        initComponents();

        DefaultTableModel model = (DefaultTableModel) tbladmindetails.getModel();
        try {
            PreparedStatement pstmt = db.cn.prepareStatement("select * from user");
            ResultSet rs = pstmt.executeQuery();
//            int i = 1;
            while (rs.next()) {
                model.addRow(new Object[]{rs.getInt(1), rs.getString(2), rs.getString(3)});
//            i++;
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbladmindetails = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/goback.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        tbladmindetails.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbladmindetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Username", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbladmindetails.setAlignmentX(1.0F);
        tbladmindetails.setAlignmentY(1.0F);
        tbladmindetails.setRowHeight(25);
        tbladmindetails.setRowMargin(2);
        tbladmindetails.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbladmindetails);
        if (tbladmindetails.getColumnModel().getColumnCount() > 0) {
            tbladmindetails.getColumnModel().getColumn(0).setResizable(false);
            tbladmindetails.getColumnModel().getColumn(0).setPreferredWidth(50);
            tbladmindetails.getColumnModel().getColumn(1).setResizable(false);
            tbladmindetails.getColumnModel().getColumn(1).setPreferredWidth(200);
            tbladmindetails.getColumnModel().getColumn(2).setResizable(false);
            tbladmindetails.getColumnModel().getColumn(2).setPreferredWidth(200);
        }

        btnDelete.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 51, 51));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        MainProgram.mainframe.mainPane.remove(this);
        MainProgram.mainframe.mainPane.add(new admindash());
        SwingUtilities.updateComponentTreeUI(MainProgram.mainframe.mainPane);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Do you want to Delete Data !!", "Delete Users", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            DefaultTableModel model = (DefaultTableModel) tbladmindetails.getModel();
            String id = model.getValueAt(tbladmindetails.getSelectedRow(), 0).toString();
            int id1 = Integer.parseInt(id);
            adminDao.deleteData(id1);

            JOptionPane.showMessageDialog(null, "Successfully Data has been deleted");
            MainProgram.mainframe.mainPane.remove(this);
            MainProgram.mainframe.mainPane.add(new LoginDetails());
            SwingUtilities.updateComponentTreeUI(MainProgram.mainframe.mainPane);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbladmindetails;
    // End of variables declaration//GEN-END:variables
}
